version: "3.8"
services:
  backend:
    image: "devmissael/springboot-react-fullstack:3.6.2022.5.18.30"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev